version: '3.4'

services:
  api-code-compass:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - .env.docker:/app/.env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - pg
      - pg_test
      - migration
    networks:
      - express-network
    command: yarn start:dev

  migration:
    build:
      context: .
      target: migrate
    volumes:
      - .:/app
      - .env.docker:/app/.env
    depends_on:
      - pg
      - pg_test
    networks:
      - express-network

  pg:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - express-network

  pg_test:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    volumes:
      - pg_test_data:/var/lib/postgresql/data
    ports:
      - '${TEST_DB_PORT}:${DB_PORT}'
    networks:
      - express-network

volumes:
  pg_data:
  pg_test_data:

networks:
  express-network:
    driver: bridge
